FROM node:22.13.1  AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN node ace build

FROM node:22.13.1  AS production

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit="dev"

COPY --from=build /app/build ./build
COPY --from=build /app/public ./public

EXPOSE 3333

CMD ["node", "build/bin/server.js"]